services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name:  arbitraje_app
    working_dir: /var/www
    volumes:
      -  ./arbitraje:/var/www
    depends_on:
      -  db

  webserver:
    image: nginx:alpine
    container_name:  arbitraje_server
    ports:
      -  "8088:80"
    volumes:
      -  ./arbitraje:/var/www
      -  ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      -  app

  db:
    image: mysql:8
    container_name: arbitraje_bd
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      -  "3308:3306"
    volumes:
      -  db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: arbitraje_phpmyadmin
    restart: always
    ports:
      - "8089:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db

volumes:
  db_data:
